{{- if .Values.redis.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "laravel-vue-app.fullname" . }}-redis
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "laravel-vue-app.labels" . | nindent 4 }}
    app: redis
spec:
  selector:
    app: redis
    {{- include "laravel-vue-app.selectorLabels" . | nindent 4 }}
  ports:
    - protocol: TCP
      port: {{ .Values.redis.port }}
      targetPort: redis
  type: ClusterIP
{{- end }}
