apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "laravel-vue-app.fullname" . }}-env
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "laravel-vue-app.labels" . | nindent 4 }}
data:
  {{- range $key, $value := .Values.env }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
