apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: laravel-ingress
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "laravel-vue-app.labels" . | nindent 4 }}
spec:
  ingressClassName: {{ .Values.ingressClassName }}
  rules:
    - host: {{ .Values.domain }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: laravel-nginx-service
                port:
                  number: 80
